version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: apimspr
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db:3306/apimspr"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
